MAIN_SIZES = {'cell_btn': (25, 25),
              'main_btn': (52, 52)}
MAIN_PATHS = {'btn_smile_happy': 'rendered_data/smile_happy.png',
              'btn_smile_happy_pressed': 'rendered_data/smile_happy_pressed.png',
              'btn_smile_win': 'rendered_data/smile_win.png',
              'btn_smile_win_pressed': 'rendered_data/smile_win_pressed.png',
              'btn_smile_surprised': 'rendered_data/smile_surprised.png',
              'btn_smile_died': 'rendered_data/smile_died.png',
              'btn_smile_died_pressed': 'rendered_data/smile_died_pressed.png',
              'switch_field_mode_beginner': 'rendered_data/difficulty_beginner.png',
              'switch_field_mode_beginner_pressed': 'rendered_data/difficulty_beginner_pressed.png',
              'switch_field_mode_amateur': 'rendered_data/difficulty_amateur.png',
              'switch_field_mode_amateur_pressed': 'rendered_data/difficulty_amateur_pressed.png',
              'switch_field_mode_professional': 'rendered_data/difficulty_professional.png',
              'switch_field_mode_professional_pressed': 'rendered_data/difficulty_professional_pressed.png',
              'switch_field_mode_superman': 'rendered_data/difficulty_superman.png',
              'switch_field_mode_superman_pressed': 'rendered_data/difficulty_superman_pressed.png',
              'switch_game_mode_random': 'rendered_data/game_mode_random.png',
              'switch_game_mode_random_pressed': 'rendered_data/game_mode_random_pressed.png',
              'switch_game_mode_safety': 'rendered_data/game_mode_safety.png',
              'switch_game_mode_safety_pressed': 'rendered_data/game_mode_safety_pressed.png',
              'switch_click_mode_first': 'rendered_data/click_mode_first.png',
              'switch_click_mode_first_pressed': 'rendered_data/click_mode_first_pressed.png',
              'switch_click_mode_second': 'rendered_data/click_mode_second.png',
              'switch_click_mode_second_pressed': 'rendered_data/click_mode_second_pressed.png',
              'cell': 'rendered_data/cell_closed.png',
              'cell_pressed': 'rendered_data/cell_opened.png',
              'cell_1': 'rendered_data/number_one.png',
              'cell_2': 'rendered_data/number_two.png',
              'cell_3': 'rendered_data/number_three.png',
              'cell_4': 'rendered_data/number_four.png',
              'cell_5': 'rendered_data/number_five.png',
              'cell_6': 'rendered_data/number_six.png',
              'cell_7': 'rendered_data/number_seven.png',
              'cell_8': 'rendered_data/number_eight.png',
              'mine_active': 'rendered_data/mine_active.png',
              'mine_default': 'rendered_data/mine_default.png',
              'mine_incorrect': 'rendered_data/mine_incorrect.png',
              'flag': 'rendered_data/flag.png'
              }
FIELD_MODES = {'0': ((9, 9), 10),
               '1': ((16, 16), 40),
               '2': ((30, 16), 99),
               '3': ((50, 50), 500)}
GAME_MODES = {'0': 'random',
              '1': 'safety'}